=== Charl12-gb/xml_cours_master_2_exo/exo1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="repertoire">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="personne" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="nom" type="xsd:string" />
                            <xsd:element name="prenom" type="xsd:string" />
                            <xsd:element name="adresse">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="pays" type="xsd:string" />
                                        <xsd:element name="departement" type="xsd:string" />
                                        <xsd:element name="ville" type="xsd:string" />
                                        <xsd:element name="maison" type="xsd:string" />
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="telephones">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="telephone" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:simpleContent>
                                                    <xsd:extension base="xsd:string">
                                                        <xsd:attribute name="type" use="required" type="xsd:string" />
                                                    </xsd:extension>
                                                </xsd:simpleContent>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="emails">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="email" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:simpleContent>
                                                    <xsd:extension base="xsd:string">
                                                        <xsd:attribute name="type" use="required" type="xsd:string" />
                                                    </xsd:extension>
                                                </xsd:simpleContent>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="sexe" use="required" type="xsd:string" />
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Charl12-gb/xml_cours_master_2_exo/exo1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<repertoire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="exo1.xsd">
    <personne sexe="Femme">
        <nom>Dassi</nom>
        <prenom>Colis</prenom>
        <adresse>
            <pays>Benin</pays>
            <departement>Litoral</departement>
            <ville>Cotonou</ville>
            <maison>Hous</maison>
        </adresse>
        <telephones>
            <telephone type="fixe">01 02 03 04 05</telephone>
            <telephone type="portable">06 07 08 09 10</telephone>
        </telephones>
        <emails>
            <email type="adresse personnelle">dassi@gmail.com</email>
            <email type="professionnelle">dassi@gmail.com</email>
        </emails>
    </personne>
    <personne sexe="Homme">
        <nom>Dupont</nom>
        <prenom>Jean</prenom>
        <adresse>
            <pays>Benin</pays>
            <departement>Litoral</departement>
            <ville>Cotonou</ville>
            <maison>Hous</maison>
        </adresse>
        <telephones>
            <telephone type="fixe">01 02 03 04 05</telephone>
        </telephones>
        <emails>
            <email type="adresse personnelle">dassi@gmail.com</email>
        </emails>
    </personne>
</repertoire>
